image: erlang:22

stages:
  - build

build:
  stage: build
  script:
    - make
    - mkdir artifacts
    - cp -a _build/default/lib/emqx_statsd artifacts
  allow_failure: true
  artifacts:
    paths:
      - artifacts/
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 hour
