image: erlang:22

stages:
  - build
  - publish


cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - _build/

build:
  stage: build
  script:
    - make
    - mkdir artifacts
    - cp -rL _build/default/lib/emqx_statsd artifacts
  allow_failure: true
  artifacts:
    paths:
      - artifacts
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 hour


publish:
  stage: publish
  script:
    - apt-get install ruby ruby-dev rubygems build-essential
    - gem install --no-document fpm
    - fpm -s dir -t tar --prefix=/usr/lib/emqx/lib -n emqx-prometheus _build/default/lib/emqx_statsd
    - fpm --verbose -s tar -t rpm -n "emqx-prometheus" -v "${VERSION}" emqx-prometheus.tar
#    - ./upload_rpms.sh -r ${RPM_REPOSITORY_ID} -f artifacts/emqx-stats*.rpm -u "${RPM_REPOSITORY_USER}" -p "${RPM_REPOSITORY_PASSWORD}"
  artifacts:
    paths:
      - artifacts/
    name: "${CI_BUILD_NAME}_${CI_BUILD_REF}"
    expire_in: 1 hour
#  only:
#    - tags
