image: erlang:22

stages:
  - build

build:
  stage: build
  script:
    - make
  allow_failure: true
  artifacts:
    paths:
      - _build/default/lib/emqx_statsd/
    name: "${CI_JOB_NAME}_${CI_COMMIT_SHA}"
    expire_in: 1 hour
